# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-16 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('cod_beneficiario', models.AutoField(db_column='CodBeneficiario', primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(blank=True, db_column='NombreCompleto', max_length=200, null=True)),
                ('parentesco', models.CharField(blank=True, db_column='Parentesco', max_length=1, null=True)),
                ('tipoid', models.CharField(blank=True, db_column='TipoId', max_length=1, null=True)),
                ('porcentaje', models.IntegerField(blank=True, db_column='Porcentaje', null=True)),
            ],
            options={
                'db_table': 'Sol].[Beneficiarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colonia',
            fields=[
                ('cod_colonia', models.AutoField(db_column='CodColonia', primary_key=True, serialize=False)),
                ('descripcion_colonia', models.CharField(blank=True, db_column='DescripcionColonia', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Sol].[Colonias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('cod_departamento', models.AutoField(db_column='CodDepartamento', primary_key=True, serialize=False)),
                ('descripcion_depto', models.CharField(blank=True, db_column='DescripcionDepto', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Sol].[Departamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dependiente',
            fields=[
                ('cod_dependiente', models.AutoField(db_column='CodDependiente', primary_key=True, serialize=False)),
                ('parentesco', models.CharField(blank=True, db_column='Parentesco', max_length=1, null=True)),
                ('tipo_id', models.CharField(blank=True, db_column='TipoId', max_length=1, null=True)),
                ('nombre_completo', models.CharField(blank=True, db_column='NombreCompleto', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Sol].[Dependientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('cod_instituciones', models.AutoField(db_column='CodInstituciones', primary_key=True, serialize=False)),
                ('descripcion_inst', models.CharField(blank=True, db_column='DescripcionInst', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Sol].[Instituciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('cod_municipio', models.AutoField(db_column='CodMunicipio', primary_key=True, serialize=False)),
                ('descripcion_municipio', models.CharField(blank=True, db_column='DescripcionMunicipio', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Sol].[Municipios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('cod_pais', models.AutoField(db_column='CodPais', primary_key=True, serialize=False)),
                ('descripcion_pais', models.CharField(blank=True, db_column='DescripcionPais', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Sol].[Paises',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('cod_referencia', models.AutoField(db_column='CodReferencia', primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(blank=True, db_column='NombreCompleto', max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=50, null=True)),
                ('familiar', models.NullBooleanField(db_column='Familiar')),
            ],
            options={
                'db_table': 'Sol].[Referencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(db_column='IdSolicitud', primary_key=True, serialize=False)),
                ('producto', models.CharField(blank=True, db_column='Producto', max_length=1, null=True)),
                ('moneda', models.CharField(blank=True, db_column='Moneda', max_length=1, null=True)),
                ('titular', models.NullBooleanField(db_column='Titular')),
                ('firma', models.NullBooleanField(db_column='Firma')),
                ('estado', models.IntegerField(blank=True, db_column='Estado', null=True)),
                ('identidad', models.CharField(blank=True, db_column='Identidad', max_length=13, null=True)),
                ('nombre_completo', models.CharField(blank=True, db_column='NombreCompleto', max_length=100, null=True)),
                ('fecha_nacimiento', models.CharField(blank=True, db_column='FechaNacimiento', max_length=10, null=True)),
                ('lugar_nacimiento', models.CharField(blank=True, db_column='LugarNacimiento', max_length=50, null=True)),
                ('nacionalidad', models.IntegerField(blank=True, db_column='Nacionalidad', null=True)),
                ('estado_civil', models.CharField(blank=True, db_column='EstadoCivil', max_length=1, null=True)),
                ('sexo', models.CharField(blank=True, db_column='Sexo', max_length=1, null=True)),
                ('nombre_conyuge', models.CharField(blank=True, db_column='NombreConyuge', max_length=100, null=True)),
                ('tipo_identificacion', models.CharField(blank=True, db_column='TipoIdentificacion', max_length=1, null=True)),
                ('rtn', models.CharField(blank=True, db_column='RTN', max_length=14, null=True)),
                ('direccion_detallada', models.CharField(blank=True, db_column='DireccionDetallada', max_length=200, null=True)),
                ('referencia', models.CharField(blank=True, db_column='Referencia', max_length=200, null=True)),
                ('casa', models.CharField(blank=True, db_column='Casa', max_length=200, null=True)),
                ('telefono_casa', models.CharField(blank=True, db_column='TelefonoCasa', max_length=20, null=True)),
                ('telefono2', models.CharField(blank=True, db_column='Telefono2', max_length=20, null=True)),
                ('celular', models.CharField(blank=True, db_column='Celular', max_length=20, null=True)),
                ('fax', models.CharField(blank=True, db_column='Fax', max_length=20, null=True)),
                ('nivel_educativo', models.CharField(blank=True, db_column='NivelEducativo', max_length=1, null=True)),
                ('correo_electronico', models.CharField(blank=True, db_column='CorreoElectronico', max_length=50, null=True)),
                ('profesion', models.CharField(blank=True, db_column='Profesion', max_length=1, null=True)),
                ('cod_actividad_economica', models.IntegerField(blank=True, db_column='CodActividadEconomica', null=True)),
                ('nombre_empresa', models.CharField(blank=True, db_column='NombreEmpresa', max_length=100, null=True)),
                ('direccion_detallada_empresa', models.CharField(blank=True, db_column='DireccionDetalladaEmpresa', max_length=200, null=True)),
                ('posicion_empresa', models.CharField(blank=True, db_column='PosicionEmpresa', max_length=50, null=True)),
                ('antiguedad_meses', models.IntegerField(blank=True, db_column='AntiguedadMeses', null=True)),
                ('comerciante_individual', models.NullBooleanField(db_column='ComercianteIndividual')),
                ('detalleo_giro', models.CharField(blank=True, db_column='DetalleoGiro', max_length=100, null=True)),
                ('nivel_ingresos_smmv', models.CharField(blank=True, db_column='NivelIngresosSMMV', max_length=1, null=True)),
                ('cargo_publico', models.NullBooleanField(db_column='CargoPublico')),
                ('cant_personas', models.IntegerField(blank=True, db_column='CantPersonas', null=True)),
                ('proposito', models.CharField(blank=True, db_column='Proposito', max_length=1, null=True)),
                ('monto_inicial', models.IntegerField(blank=True, db_column='MontoInicial', null=True)),
                ('origen_deposito', models.CharField(blank=True, db_column='OrigenDeposito', max_length=1, null=True)),
                ('monto_mensual_estimado', models.IntegerField(blank=True, db_column='MontoMensualEstimado', null=True)),
            ],
            options={
                'db_table': 'Sol].[Solicitudes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Actividadeseconomicas',
            fields=[
                ('cod_actividad_economica', models.ForeignKey(db_column='CodActividadEconomica', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='general.Solicitud')),
                ('desc_actividad', models.CharField(blank=True, db_column='DescActividad', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'Sol].[ActividadesEconomicas',
                'managed': False,
            },
        ),
    ]
